const jobs = [
  {
    title: 'Frontend Developer Intern',
    company: 'TechStart Inc',
    location: 'Remote',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    requiredSkills: ['HTML', 'CSS', 'JavaScript', 'React'],
    applyLinks: [
      { platform: 'LinkedIn', url: 'https://linkedin.com/jobs/view/123' },
      { platform: 'BDJobs', url: 'https://bdjobs.com' },
    ],
    description: 'Build responsive UIs for our SaaS product.',
  },
  {
    title: 'Junior Web Developer',
    company: 'Digital Solutions',
    location: 'Dhaka',
    jobType: 'Full-time',
    experienceLevel: 'Junior',
    requiredSkills: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    applyLinks: [{ platform: 'LinkedIn', url: 'https://linkedin.com' }],
    description: 'Full-stack web development role.',
  },
  {
    title: 'React Developer',
    company: 'Innovate Labs',
    location: 'Remote',
    jobType: 'Part-time',
    experienceLevel: 'Fresher',
    requiredSkills: ['React', 'JavaScript', 'CSS', 'Git'],
    applyLinks: [{ platform: 'BDJobs', url: 'https://bdjobs.com' }],
    description: 'Part-time React development for startups.',
  },
  {
    title: 'Backend Developer Intern',
    company: 'DataFlow Systems',
    location: 'Chittagong',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    requiredSkills: ['Node.js', 'MongoDB', 'Express', 'REST API'],
    applyLinks: [{ platform: 'LinkedIn', url: 'https://linkedin.com' }],
    description: 'Build REST APIs and work with MongoDB.',
  },
  {
    title: 'Full Stack Developer',
    company: 'CloudNine',
    location: 'Remote',
    jobType: 'Full-time',
    experienceLevel: 'Junior',
    requiredSkills: ['React', 'Node.js', 'MongoDB', 'TypeScript'],
    applyLinks: [
      { platform: 'LinkedIn', url: 'https://linkedin.com' },
      { platform: 'BDJobs', url: 'https://bdjobs.com' },
    ],
    description: 'End-to-end web development.',
  },
  {
    title: 'UI/UX Design Intern',
    company: 'Creative Agency',
    location: 'Dhaka',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    requiredSkills: ['Figma', 'UI', 'UX', 'Design'],
    applyLinks: [{ platform: 'BDJobs', url: 'https://bdjobs.com' }],
    description: 'Design user interfaces and prototypes.',
  },
  {
    title: 'Data Analyst Junior',
    company: 'Analytics Pro',
    location: 'Remote',
    jobType: 'Full-time',
    experienceLevel: 'Junior',
    requiredSkills: ['SQL', 'Excel', 'Python', 'Data Analysis'],
    applyLinks: [{ platform: 'LinkedIn', url: 'https://linkedin.com' }],
    description: 'Analyze data and create reports.',
  },
  {
    title: 'Freelance Web Developer',
    company: 'Upwork Client',
    location: 'Remote',
    jobType: 'Freelance',
    experienceLevel: 'Fresher',
    requiredSkills: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
    applyLinks: [{ platform: 'Upwork', url: 'https://upwork.com' }],
    description: 'Freelance web development projects.',
  },
  {
    title: 'Junior Frontend Engineer',
    company: 'E-commerce Co',
    location: 'Dhaka',
    jobType: 'Full-time',
    experienceLevel: 'Junior',
    requiredSkills: ['React', 'Redux', 'Tailwind', 'TypeScript'],
    applyLinks: [{ platform: 'BDJobs', url: 'https://bdjobs.com' }],
    description: 'Build e-commerce frontend features.',
  },
  {
    title: 'Python Developer Intern',
    company: 'AI Startup',
    location: 'Remote',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    requiredSkills: ['Python', 'Django', 'SQL', 'REST API'],
    applyLinks: [{ platform: 'LinkedIn', url: 'https://linkedin.com' }],
    description: 'Backend development with Python.',
  },
  {
    title: 'Mobile App Developer',
    company: 'AppWorks',
    location: 'Remote',
    jobType: 'Part-time',
    experienceLevel: 'Junior',
    requiredSkills: ['React Native', 'JavaScript', 'Firebase'],
    applyLinks: [{ platform: 'BDJobs', url: 'https://bdjobs.com' }],
    description: 'Cross-platform mobile development.',
  },
  {
    title: 'Junior Data Scientist',
    company: 'DataViz Inc',
    location: 'Dhaka',
    jobType: 'Full-time',
    experienceLevel: 'Junior',
    requiredSkills: ['Python', 'Pandas', 'Machine Learning', 'SQL'],
    applyLinks: [
      { platform: 'LinkedIn', url: 'https://linkedin.com' },
      { platform: 'BDJobs', url: 'https://bdjobs.com' },
    ],
    description: 'Data analysis and ML models.',
  },
  {
    title: 'WordPress Developer',
    company: 'Web Agency',
    location: 'Remote',
    jobType: 'Freelance',
    experienceLevel: 'Fresher',
    requiredSkills: ['WordPress', 'PHP', 'HTML', 'CSS'],
    applyLinks: [{ platform: 'Upwork', url: 'https://upwork.com' }],
    description: 'WordPress theme and plugin development.',
  },
  {
    title: 'Frontend Developer',
    company: 'FinTech Solutions',
    location: 'Dhaka',
    jobType: 'Full-time',
    experienceLevel: 'Mid',
    requiredSkills: ['React', 'TypeScript', 'CSS', 'Testing'],
    applyLinks: [{ platform: 'LinkedIn', url: 'https://linkedin.com' }],
    description: 'Build financial dashboards.',
  },
  {
    title: 'Graphic Design Intern',
    company: 'Brand Studio',
    location: 'Chittagong',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    requiredSkills: ['Figma', 'Adobe Illustrator', 'Design'],
    applyLinks: [{ platform: 'BDJobs', url: 'https://bdjobs.com' }],
    description: 'Brand and marketing design.',
  },
  {
    title: 'DevOps Intern',
    company: 'CloudFirst',
    location: 'Remote',
    jobType: 'Internship',
    experienceLevel: 'Fresher',
    requiredSkills: ['Docker', 'Linux', 'AWS', 'CI/CD'],
    applyLinks: [{ platform: 'LinkedIn', url: 'https://linkedin.com' }],
    description: 'Infrastructure and deployment.',
  },
  {
    title: 'Content Writer + SEO',
    company: 'Content Hub',
    location: 'Remote',
    jobType: 'Part-time',
    experienceLevel: 'Fresher',
    requiredSkills: ['SEO', 'Content Writing', 'Excel'],
    applyLinks: [{ platform: 'BDJobs', url: 'https://bdjobs.com' }],
    description: 'Content creation and SEO optimization.',
  },
  {
    title: 'Junior QA Engineer',
    company: 'Quality Labs',
    location: 'Dhaka',
    jobType: 'Full-time',
    experienceLevel: 'Fresher',
    requiredSkills: ['Testing', 'Jest', 'Cypress', 'JavaScript'],
    applyLinks: [{ platform: 'LinkedIn', url: 'https://linkedin.com' }],
    description: 'Manual and automated testing.',
  },
  {
    title: 'Vue.js Developer',
    company: 'Modern Web Co',
    location: 'Remote',
    jobType: 'Full-time',
    experienceLevel: 'Junior',
    requiredSkills: ['Vue', 'JavaScript', 'CSS', 'API'],
    applyLinks: [{ platform: 'BDJobs', url: 'https://bdjobs.com' }],
    description: 'Vue.js SPA development.',
  },
  {
    title: 'Junior Product Designer',
    company: 'Product Studio',
    location: 'Remote',
    jobType: 'Full-time',
    experienceLevel: 'Junior',
    requiredSkills: ['Figma', 'UI', 'UX', 'Prototyping'],
    applyLinks: [
      { platform: 'LinkedIn', url: 'https://linkedin.com' },
      { platform: 'BDJobs', url: 'https://bdjobs.com' },
    ],
    description: 'Product design and user research.',
  },
];

module.exports = { jobs };
