import { useEffect, useState, useRef } from 'react';
import { useParams, Link } from 'react-router-dom';
import Layout from '../components/Layout';
import { getRoadmapById } from '../services/api';

export default function RoadmapView() {
  const { id } = useParams();
  const [roadmap, setRoadmap] = useState(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const printRef = useRef(null);

  const totalWeeks = roadmap?.steps?.length ? Math.max(...roadmap.steps.map((step) => Number(step.week) || 0)) : 0;
  const totalTasks = roadmap?.steps?.reduce((acc, step) => acc + (step.tasks?.length || 0), 0) || 0;

  useEffect(() => {
    if (!id) return;
    getRoadmapById(id)
      .then((res) => setRoadmap(res.data))
      .catch(() => setRoadmap(null))
      .finally(() => setLoading(false));
  }, [id]);

  const downloadPDF = async () => {
    if (!roadmap) return;
    setDownloading(true);
    
    try {
      // Create a printable HTML document
      const printContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>${roadmap.targetRole} - Career Roadmap</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1a1a1a; line-height: 1.6; }
            .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #0891b2; }
            .header h1 { font-size: 28px; color: #0891b2; margin-bottom: 8px; }
            .header p { color: #666; font-size: 14px; }
            .stats { display: flex; justify-content: center; gap: 40px; margin-bottom: 40px; }
            .stat { text-align: center; }
            .stat-value { font-size: 24px; font-weight: bold; color: #0891b2; }
            .stat-label { font-size: 12px; color: #666; text-transform: uppercase; }
            .week-card { margin-bottom: 24px; page-break-inside: avoid; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }
            .week-header { background: linear-gradient(135deg, #0891b2 0%, #7c3aed 100%); color: white; padding: 12px 20px; }
            .week-header h3 { font-size: 16px; font-weight: 600; }
            .week-body { padding: 20px; }
            .tasks-title { font-size: 12px; font-weight: 600; color: #666; text-transform: uppercase; margin-bottom: 12px; }
            .task { display: flex; align-items: flex-start; gap: 10px; margin-bottom: 8px; }
            .task-bullet { width: 6px; height: 6px; background: #0891b2; border-radius: 50%; margin-top: 6px; flex-shrink: 0; }
            .task-text { font-size: 14px; color: #374151; }
            .projects { margin-top: 16px; padding-top: 16px; border-top: 1px solid #e5e7eb; }
            .projects-title { font-size: 12px; font-weight: 600; color: #666; text-transform: uppercase; margin-bottom: 8px; }
            .project-tag { display: inline-block; background: #f0fdf4; color: #166534; padding: 4px 12px; border-radius: 20px; font-size: 12px; margin-right: 8px; margin-bottom: 4px; }
            .tip { margin-top: 16px; padding: 12px; background: #fffbeb; border-left: 3px solid #f59e0b; border-radius: 0 8px 8px 0; }
            .tip-text { font-size: 13px; color: #92400e; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px; }
            @media print { body { padding: 20px; } .week-card { break-inside: avoid; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${roadmap.targetRole}</h1>
            <p>${roadmap.duration}-Month Learning Roadmap • Generated by NextCareer</p>
          </div>
          <div class="stats">
            <div class="stat">
              <div class="stat-value">${totalWeeks}</div>
              <div class="stat-label">Total Weeks</div>
            </div>
            <div class="stat">
              <div class="stat-value">${roadmap.duration}</div>
              <div class="stat-label">Months</div>
            </div>
            <div class="stat">
              <div class="stat-value">${totalTasks}</div>
              <div class="stat-label">Tasks</div>
            </div>
          </div>
          ${roadmap.steps?.map((step) => `
            <div class="week-card">
              <div class="week-header">
                <h3>Week ${step.week}: ${step.topic}</h3>
              </div>
              <div class="week-body">
                <div class="tasks-title">Learning Tasks</div>
                ${(step.tasks || []).map(t => `
                  <div class="task">
                    <div class="task-bullet"></div>
                    <div class="task-text">${t}</div>
                  </div>
                `).join('')}
                ${(step.projectIdeas || []).length > 0 ? `
                  <div class="projects">
                    <div class="projects-title">Project Ideas</div>
                    ${step.projectIdeas.map(p => `<span class="project-tag">${p}</span>`).join('')}
                  </div>
                ` : ''}
                ${step.jobApplicationTip ? `
                  <div class="tip">
                    <div class="tip-text">💡 ${step.jobApplicationTip}</div>
                  </div>
                ` : ''}
              </div>
            </div>
          `).join('') || ''}
          <div class="footer">
            <p>This roadmap was generated by NextCareer AI • ${new Date().toLocaleDateString()}</p>
            <p>Adjust the pace based on your schedule and prior knowledge.</p>
          </div>
        </body>
        </html>
      `;

      // Open print dialog
      const printWindow = window.open('', '_blank');
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.focus();
      
      // Wait for content to load then print
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 250);
    } catch (err) {
      console.error('PDF generation failed:', err);
    } finally {
      setDownloading(false);
    }
  };

  if (loading) return (
    <Layout>
      <div className="min-h-screen bg-gradient-to-br from-[#0a0f1a] via-[#0d1526] to-[#1a1033] -mx-4 -mt-8 px-4 py-8">
        <div className="flex items-center justify-center gap-3 py-20">
          <svg className="animate-spin h-6 w-6 text-cyan-400" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          <span className="text-gray-400 text-lg">Loading roadmap...</span>
        </div>
      </div>
    </Layout>
  );

  if (!roadmap) return (
    <Layout>
      <div className="min-h-screen bg-gradient-to-br from-[#0a0f1a] via-[#0d1526] to-[#1a1033] -mx-4 -mt-8 px-4 py-8">
        <div className="max-w-2xl mx-auto text-center py-20">
          <div className="w-20 h-20 mx-auto bg-slate-800/50 rounded-2xl flex items-center justify-center border border-white/10 mb-6">
            <svg className="w-10 h-10 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
            </svg>
          </div>
          <p className="text-gray-400 text-lg mb-6">Roadmap not found</p>
          <Link 
            to="/dashboard" 
            className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-cyan-500 to-blue-600 text-white font-medium rounded-xl hover:shadow-lg hover:shadow-cyan-500/25 transition-all"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to Dashboard
          </Link>
        </div>
      </div>
    </Layout>
  );

  return (
    <Layout>
      <div className="min-h-screen bg-gradient-to-br from-[#0a0f1a] via-[#0d1526] to-[#1a1033] -mx-4 -mt-8 px-4 py-8 sm:px-6 lg:px-8">
        {/* Ambient glow effects */}
        <div className="fixed inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-20 left-1/4 w-96 h-96 bg-cyan-500/8 rounded-full blur-3xl" />
          <div className="absolute bottom-1/3 right-1/4 w-80 h-80 bg-purple-500/8 rounded-full blur-3xl" />
        </div>

        <div className="max-w-4xl mx-auto relative z-10" ref={printRef}>
          {/* Back Link */}
          <Link 
            to="/dashboard" 
            className="inline-flex items-center gap-2 text-gray-400 hover:text-cyan-400 text-sm font-medium mb-6 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to Dashboard
          </Link>
          
          {/* Header Card */}
          <div className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-6 sm:p-8 mb-8 shadow-[0_0_40px_rgba(0,0,0,0.4)]">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
              <div className="flex items-center gap-4">
                <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-emerald-500/20 to-teal-500/20 flex items-center justify-center border border-emerald-500/30">
                  <svg className="w-7 h-7 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
                  </svg>
                </div>
                <div>
                  <h1 className="text-2xl sm:text-3xl font-bold text-white">{roadmap.targetRole}</h1>
                  <p className="text-gray-400 mt-1">{roadmap.duration}-month learning roadmap</p>
                </div>
              </div>
              <button
                onClick={downloadPDF}
                disabled={downloading}
                className="inline-flex items-center justify-center gap-2 px-5 py-3 bg-gradient-to-r from-cyan-500 to-purple-600 text-white font-medium rounded-xl hover:shadow-lg hover:shadow-cyan-500/25 hover:scale-[1.02] transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {downloading ? (
                  <>
                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                    </svg>
                    Generating...
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download PDF
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Progress Stats */}
          <div className="grid grid-cols-3 gap-4 mb-8">
            <div className="bg-white/5 backdrop-blur-xl rounded-xl border border-white/10 p-5 text-center hover:border-cyan-500/30 transition-all">
              <p className="text-3xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">{totalWeeks}</p>
              <p className="text-sm text-gray-400 mt-1">Total Weeks</p>
            </div>
            <div className="bg-white/5 backdrop-blur-xl rounded-xl border border-white/10 p-5 text-center hover:border-purple-500/30 transition-all">
              <p className="text-3xl font-bold bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">{roadmap.duration}</p>
              <p className="text-sm text-gray-400 mt-1">Months</p>
            </div>
            <div className="bg-white/5 backdrop-blur-xl rounded-xl border border-white/10 p-5 text-center hover:border-emerald-500/30 transition-all">
              <p className="text-3xl font-bold bg-gradient-to-r from-emerald-400 to-teal-500 bg-clip-text text-transparent">{totalTasks}</p>
              <p className="text-sm text-gray-400 mt-1">Tasks</p>
            </div>
          </div>

          {/* Timeline */}
          <div className="relative">
            {/* Vertical line */}
            <div className="absolute left-6 top-0 bottom-0 w-0.5 bg-gradient-to-b from-cyan-500/50 via-purple-500/50 to-emerald-500/50 hidden sm:block" />

            <div className="space-y-6">
              {roadmap.steps?.map((step, i) => (
                <div key={i} className="relative flex gap-6">
                  {/* Timeline dot */}
                  <div className="hidden sm:flex shrink-0 w-12 h-12 bg-gradient-to-br from-cyan-500/20 to-purple-500/20 backdrop-blur-xl rounded-full items-center justify-center z-10 border border-cyan-500/30">
                    <span className="text-cyan-400 font-bold text-sm">{step.week}</span>
                  </div>

                  {/* Card */}
                  <div className="flex-1 bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 overflow-hidden shadow-lg hover:border-cyan-500/20 hover:shadow-[0_0_30px_rgba(6,182,212,0.1)] transition-all duration-300 hover:-translate-y-0.5">
                    <div className="p-5 sm:p-6">
                      <div className="flex items-start justify-between gap-3 mb-4">
                        <div>
                          <span className="sm:hidden inline-block px-3 py-1 bg-gradient-to-r from-cyan-500/20 to-blue-500/20 text-cyan-300 text-xs font-semibold rounded-full border border-cyan-500/30 mb-3">
                            Week {step.week}
                          </span>
                          <h3 className="font-semibold text-white text-lg">{step.topic}</h3>
                        </div>
                      </div>

                      {/* Tasks */}
                      <div className="space-y-3 mb-4">
                        {(step.tasks || []).map((t, j) => (
                          <div key={j} className="flex items-start gap-3 group">
                            <div className="shrink-0 mt-2 w-2 h-2 bg-cyan-400 rounded-full group-hover:shadow-[0_0_8px_rgba(6,182,212,0.6)] transition-shadow" />
                            <span className="text-sm text-gray-300 leading-relaxed">{t}</span>
                          </div>
                        ))}
                      </div>

                      {/* Project Ideas */}
                      {(step.projectIdeas || []).length > 0 && (
                        <div className="pt-4 border-t border-white/10">
                          <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">Project Ideas</p>
                          <div className="flex flex-wrap gap-2">
                            {step.projectIdeas.map((p, k) => (
                              <span key={k} className="text-xs bg-gradient-to-r from-emerald-500/20 to-teal-500/20 text-emerald-300 px-3 py-1.5 rounded-full font-medium border border-emerald-500/30">
                                {p}
                              </span>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Job Tip */}
                      {step.jobApplicationTip && (
                        <div className="mt-4 p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl">
                          <p className="text-sm text-amber-300 flex items-start gap-3">
                            <svg className="w-5 h-5 shrink-0 mt-0.5 text-amber-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                            </svg>
                            <span>{step.jobApplicationTip}</span>
                          </p>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Footer note */}
          <div className="mt-10 p-5 bg-white/5 backdrop-blur-xl border border-white/10 rounded-xl">
            <p className="text-sm text-gray-400 text-center leading-relaxed">
              This roadmap is a personalized guide generated by NextCareer AI. Adjust the pace based on your schedule and prior knowledge. 
              For personalized mentorship, consider connecting with industry professionals.
            </p>
          </div>
        </div>
      </div>
    </Layout>
  );
}
